---
- name: "waybar | {{ ansible_distribution }} | Install waybar"
  ansible.builtin.apt:
    name: waybar
    state: present
  become: true


- name: "waybar | Ensure waybar directory structure exists"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - ~/.config
    - ~/.config/waybar


- name: "Copy scripts folder"
  ansible.builtin.copy:
    src: scripts/
    dest: ~/.config/waybar/scripts/
    mode: "0755"
    directory_mode: "0755"

- name: "waybar | Copy config files"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/.config/waybar/{{ item }}"
    mode: "0644"
  loop:
    - config
    - style.css