[window.padding]
x = 14
y = 14

[window]
decorations = "Buttonless"
opacity = 0.9
blur = true
option_as_alt = "Both"

[font.normal]
#family = "JetBrainsMono NFM SemiBold"
#family = "Cascadia Mono"
#family = "IBM Plex Mono"
family = "FiraCode Nerd Font"
style = "Bold"

[font]
size = 10

[colors.primary]
background = "0x1e1e2e"
foreground = "0xcdd6f4"

[colors.normal]
black   = "0x45475a"
red     = "0xf38ba8"
green   = "0xa6e3a1"
yellow  = "0xf9e2af"
blue    = "0x89b4fa"
magenta = "0xcba6f7"
cyan    = "0x94e2d5"
white   = "0xbac2de"

[colors.bright]
black   = "0x585b70"
red     = "0xf38ba8"
green   = "0xa6e3a1"
yellow  = "0xf9e2af"
blue    = "0x89b4fa"
magenta = "0xcba6f7"
cyan    = "0x94e2d5"
white   = "0xa6adc8"

[colors.cursor]
text = "0x1e1e2e"
cursor = "0xf5e0dc"

[colors.selection]
text = "0x1e1e2e"
background = "0xf5e0dc"

