---
- name: "sway-base | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: sway_base_distribution_config
  
- name: "sway-base | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: sway_base_distribution_config.stat.exists


# sway \
# swaybg \
# swayidle \
# swaylock \
# waybar \
# xwayland \
# wl-clipboard \
# grim \
# slurp \
# alacritty

# App-Luncher = fuzzel, wenn das nicht gut funktioniert wofi(rofi f√ºr wayland)
# Bar = waybar